Add polls to web page
eash130/step pull request #16
Opened 2020-06-10 13:53 UTC by eash130

2020-06-10 14:27 UTC, prabenzom requested changes

2020-06-10 14:27 UTC, prabenzom commented on portfolio/src/main/java/com/google/sps/servlets/PollServlet.java
> +  private Map<String, Map<String, Integer>> polls = new HashMap<>();
Is your plan to store this data in a database?

2020-06-10 14:27 UTC, prabenzom commented on portfolio/src/main/java/com/google/sps/servlets/PollServlet.java
> +      int currentVotes = poll.containsKey(pollResponse) ? poll.get(pollResponse) : 0;
You might want to standardize this data for capitalization (equalsIgnoreCase) as a simple optimization.

2020-06-10 21:13 UTC, eash130 commented on portfolio/src/main/java/com/google/sps/servlets/PollServlet.java
> +  private Map<String, Map<String, Integer>> polls = new HashMap<>();
Fixed. (finally)

2020-06-10 21:13 UTC, eash130 commented on portfolio/src/main/java/com/google/sps/servlets/PollServlet.java
> +      int currentVotes = poll.containsKey(pollResponse) ? poll.get(pollResponse) : 0;
Done.

2020-06-11 16:34 UTC, alygerharter approved these changes

2020-06-11 17:56 UTC, prabenzom approved these changes

2020-06-11 18:00 UTC, merged